name: Build and push Docker image

permissions:
  contents: read
  id-token: 'write'

on:
  push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: "actions/checkout@v2"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/248178295773/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
          service_account: 'test-wif@makefile-378011.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Configure Docker
        run: make authenticate-to-registry

      - name: Build and push Docker image
        run: make build-and-push-image